services:
  backend:
    build: ./backend
    container_name: carbonpilot-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carbonpilot
      - DEBUG=true
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "sleep 10 && 
             python -m alembic upgrade head && 
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-alpine
    container_name: carbonpilot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=carbonpilot
    restart: unless-stopped

volumes:
  postgres_data: 