# Configurazione cache condivisa
x-build-cache: &build-cache
  cache_from:
    - type=local,src=./.docker-cache
  cache_to:
    - type=local,dest=./.docker-cache

services:
  backend:
    build:
      context: ./backend
      <<: *build-cache
    container_name: carbonpilot-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carbonpilot
      - DEBUG=true
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "db", "5432"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      <<: *build-cache
    container_name: carbonpilot-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://carbonpilot-backend:8000/api
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: carbonpilot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=carbonpilot
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  carbonpilot-network:
    driver: bridge 