"""Fix Tool-Parte relationship

Revision ID: b175b50a97e9
Revises: 53a079abbcc3
Create Date: 2025-05-20 09:49:11.710120+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b175b50a97e9'
down_revision = '53a079abbcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 