"""init schema

Revision ID: 99248a67c2a3
Revises: 
Create Date: 2025-05-20 20:05:28.497769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99248a67c2a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Creo l'enum per lo stato dell'autoclave
    op.create_table(
        'autoclavi',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('codice', sa.String(length=50), nullable=False),
        sa.Column('lunghezza', sa.Float(), nullable=False),
        sa.Column('larghezza_piano', sa.Float(), nullable=False),
        sa.Column('num_linee_vuoto', sa.Integer(), nullable=False),
        sa.Column('temperatura_max', sa.Float(), nullable=False),
        sa.Column('pressione_max', sa.Float(), nullable=False),
        sa.Column('stato', postgresql.ENUM('DISPONIBILE', 'IN_USO', 'MANUTENZIONE', 'GUASTO', 'SPENTA', name='statoautoclave'), nullable=False),
        sa.Column('produttore', sa.String(length=100), nullable=True),
        sa.Column('anno_produzione', sa.Integer(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codice'),
        sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_autoclavi_id'), 'autoclavi', ['id'], unique=False)
    
    op.create_table(
        'cataloghi',
        sa.Column('part_number', sa.String(length=50), nullable=False),
        sa.Column('descrizione', sa.Text(), nullable=False),
        sa.Column('categoria', sa.String(length=100), nullable=True),
        sa.Column('attivo', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('part_number')
    )
    op.create_index(op.f('ix_cataloghi_part_number'), 'cataloghi', ['part_number'], unique=False)
    
    op.create_table(
        'cicli_cura',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('temperatura_stasi1', sa.Float(), nullable=False),
        sa.Column('pressione_stasi1', sa.Float(), nullable=False),
        sa.Column('durata_stasi1', sa.Integer(), nullable=False),
        sa.Column('attiva_stasi2', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('temperatura_stasi2', sa.Float(), nullable=True),
        sa.Column('pressione_stasi2', sa.Float(), nullable=True),
        sa.Column('durata_stasi2', sa.Integer(), nullable=True),
        sa.Column('descrizione', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_cicli_cura_id'), 'cicli_cura', ['id'], unique=False)
    
    op.create_table(
        'tools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codice', sa.String(length=50), nullable=False),
        sa.Column('descrizione', sa.Text(), nullable=True),
        sa.Column('lunghezza_piano', sa.Float(), nullable=False),
        sa.Column('larghezza_piano', sa.Float(), nullable=False),
        sa.Column('disponibile', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('in_manutenzione', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codice')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    
    op.create_table(
        'parti',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('part_number', sa.String(length=50), nullable=False),
        sa.Column('descrizione_breve', sa.String(length=255), nullable=False),
        sa.Column('num_valvole_richieste', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('ciclo_cura_id', sa.Integer(), nullable=True),
        sa.Column('note_produzione', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['ciclo_cura_id'], ['cicli_cura.id'], ),
        sa.ForeignKeyConstraint(['part_number'], ['cataloghi.part_number'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parti_id'), 'parti', ['id'], unique=False)
    op.create_index(op.f('ix_parti_part_number'), 'parti', ['part_number'], unique=False)
    
    op.create_table(
        'parte_tool_association',
        sa.Column('parte_id', sa.Integer(), nullable=False),
        sa.Column('tool_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['parte_id'], ['parti.id'], ),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
        sa.PrimaryKeyConstraint('parte_id', 'tool_id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 