"""Add Catalogo-Parti relationship

Revision ID: 983c24c9692a
Revises: b175b50a97e9
Create Date: 2025-05-20 09:50:37.821855+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983c24c9692a'
down_revision = 'b175b50a97e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 