"""Fix Parte dependencies

Revision ID: 53a079abbcc3
Revises: ef0ee71e4106
Create Date: 2025-05-20 09:38:32.612894+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a079abbcc3'
down_revision = 'ef0ee71e4106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 