"""Fix Parte dependencies

Revision ID: ef0ee71e4106
Revises: a40a5ef6af39
Create Date: 2025-05-20 09:38:22.057024+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0ee71e4106'
down_revision = 'a40a5ef6af39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 