"""Add system_logs table

Revision ID: 1313c0186228
Revises: b6976790b87b
Create Date: 2025-05-26 12:53:34.185190

"""
from alembic import op
import sqlalchemy as sa
pass

# revision identifiers, used by Alembic.
revision = '1313c0186228'
down_revision = 'b6976790b87b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('event_type', sa.Enum('ODL_STATE_CHANGE', 'NESTING_CONFIRM', 'NESTING_MODIFY', 'CURA_START', 'CURA_COMPLETE', 'TOOL_MODIFY', 'AUTOCLAVE_MODIFY', 'CICLO_MODIFY', 'BACKUP_CREATE', 'BACKUP_RESTORE', 'USER_LOGIN', 'USER_LOGOUT', 'SYSTEM_ERROR', name='eventtype'), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'MANAGEMENT', 'CLEAN_ROOM', 'CURING', 'SISTEMA', name='userrole'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_entity_id'), 'system_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_system_logs_event_type'), 'system_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_user_role'), 'system_logs', ['user_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_user_role'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_event_type'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_entity_id'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
