"""Refactor Tool, Autoclave, CicloCura fields

Revision ID: 2030_refactor_models
Revises: 1945_initial_models
Create Date: 2025-05-19 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2030_refactor_models'
down_revision = '1945_initial_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Modifica Autoclave: rimuove diametro, aggiunge larghezza_piano
    op.drop_column('autoclavi', 'diametro')
    op.add_column('autoclavi', sa.Column('larghezza_piano', sa.Float(), nullable=False, 
                                        server_default='0', 
                                        comment='Larghezza utile del piano di carico'))
    op.alter_column('autoclavi', 'larghezza_piano', server_default=None)
    
    # Modifica Tool: rimuove lunghezza, larghezza, altezza, aggiunge lunghezza_piano e larghezza_piano
    op.drop_column('tools', 'lunghezza')
    op.drop_column('tools', 'larghezza')
    op.drop_column('tools', 'altezza')
    op.add_column('tools', sa.Column('lunghezza_piano', sa.Float(), nullable=False, 
                                    server_default='0', 
                                    comment='Lunghezza utile del tool'))
    op.add_column('tools', sa.Column('larghezza_piano', sa.Float(), nullable=False, 
                                   server_default='0', 
                                   comment='Larghezza utile del tool'))
    op.alter_column('tools', 'lunghezza_piano', server_default=None)
    op.alter_column('tools', 'larghezza_piano', server_default=None)
    
    # Modifica CicloCura: rimuove tempo_totale e stasi1_*, stasi2_*, aggiunge nuovi campi per stasi
    with op.batch_alter_table('cicli_cura') as batch_op:
        # Rimuovere vecchi campi
        batch_op.drop_column('tempo_totale')
        batch_op.drop_column('stasi1_attiva')
        batch_op.drop_column('stasi1_temperatura')
        batch_op.drop_column('stasi1_pressione')
        batch_op.drop_column('stasi1_durata')
        batch_op.drop_column('stasi2_attiva')
        batch_op.drop_column('stasi2_temperatura')
        batch_op.drop_column('stasi2_pressione')
        batch_op.drop_column('stasi2_durata')
        
        # Aggiungere nuovi campi
        batch_op.add_column(sa.Column('temperatura_stasi1', sa.Float(), nullable=False, 
                                    server_default='0', 
                                    comment='Temperatura della prima stasi in gradi Celsius'))
        batch_op.add_column(sa.Column('pressione_stasi1', sa.Float(), nullable=False, 
                                    server_default='0', 
                                    comment='Pressione della prima stasi in bar'))
        batch_op.add_column(sa.Column('durata_stasi1', sa.Integer(), nullable=False, 
                                    server_default='0', 
                                    comment='Durata della prima stasi in minuti'))
        batch_op.add_column(sa.Column('attiva_stasi2', sa.Boolean(), nullable=False, 
                                    server_default='false', 
                                    comment='Indica se è presente la seconda stasi'))
        batch_op.add_column(sa.Column('temperatura_stasi2', sa.Float(), nullable=True, 
                                    comment='Temperatura della seconda stasi in gradi Celsius'))
        batch_op.add_column(sa.Column('pressione_stasi2', sa.Float(), nullable=True, 
                                    comment='Pressione della seconda stasi in bar'))
        batch_op.add_column(sa.Column('durata_stasi2', sa.Integer(), nullable=True, 
                                    comment='Durata della seconda stasi in minuti'))
        
        # Rimuovere i server_default
        batch_op.alter_column('temperatura_stasi1', server_default=None)
        batch_op.alter_column('pressione_stasi1', server_default=None)
        batch_op.alter_column('durata_stasi1', server_default=None)
        batch_op.alter_column('attiva_stasi2', server_default=None)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ripristina CicloCura
    with op.batch_alter_table('cicli_cura') as batch_op:
        # Rimuovere nuovi campi
        batch_op.drop_column('temperatura_stasi1')
        batch_op.drop_column('pressione_stasi1')
        batch_op.drop_column('durata_stasi1')
        batch_op.drop_column('attiva_stasi2')
        batch_op.drop_column('temperatura_stasi2')
        batch_op.drop_column('pressione_stasi2')
        batch_op.drop_column('durata_stasi2')
        
        # Aggiungere vecchi campi
        batch_op.add_column(sa.Column('tempo_totale', sa.Integer(), nullable=False, 
                                    server_default='0'))
        batch_op.add_column(sa.Column('stasi1_attiva', sa.Boolean(), nullable=False, 
                                    server_default='true'))
        batch_op.add_column(sa.Column('stasi1_temperatura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stasi1_pressione', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stasi1_durata', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stasi2_attiva', sa.Boolean(), nullable=False, 
                                    server_default='false'))
        batch_op.add_column(sa.Column('stasi2_temperatura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stasi2_pressione', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stasi2_durata', sa.Integer(), nullable=True))
        
        # Rimuovere i server_default
        batch_op.alter_column('tempo_totale', server_default=None)
        batch_op.alter_column('stasi1_attiva', server_default=None)
        batch_op.alter_column('stasi2_attiva', server_default=None)
    
    # Ripristina Tool
    op.drop_column('tools', 'lunghezza_piano')
    op.drop_column('tools', 'larghezza_piano')
    op.add_column('tools', sa.Column('lunghezza', sa.Float(), nullable=False, server_default='0'))
    op.add_column('tools', sa.Column('larghezza', sa.Float(), nullable=False, server_default='0'))
    op.add_column('tools', sa.Column('altezza', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('tools', 'lunghezza', server_default=None)
    op.alter_column('tools', 'larghezza', server_default=None)
    op.alter_column('tools', 'altezza', server_default=None)
    
    # Ripristina Autoclave
    op.drop_column('autoclavi', 'larghezza_piano')
    op.add_column('autoclavi', sa.Column('diametro', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('autoclavi', 'diametro', server_default=None)
    
    # ### end Alembic commands ### 