"""Fix Parte dependencies

Revision ID: a40a5ef6af39
Revises: c87c5aa1dd0c
Create Date: 2025-05-20 09:38:14.616871+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40a5ef6af39'
down_revision = 'c87c5aa1dd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 