"""create_all_tables_complete

Revision ID: cab7498e8461
Revises: cde8d3dc11af
Create Date: 2025-05-26 01:05:14.422016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cab7498e8461'
down_revision = 'cde8d3dc11af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoclavi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('codice', sa.String(length=50), nullable=True),
    sa.Column('lunghezza', sa.Float(), nullable=True),
    sa.Column('larghezza_piano', sa.Float(), nullable=True),
    sa.Column('num_linee_vuoto', sa.Integer(), nullable=True),
    sa.Column('temperatura_max', sa.Float(), nullable=True),
    sa.Column('pressione_max', sa.Float(), nullable=True),
    sa.Column('stato', postgresql.ENUM('DISPONIBILE', 'IN_USO', 'MANUTENZIONE', 'GUASTO', 'SPENTA', name='statoautoclave'), nullable=False),
    sa.Column('produttore', sa.String(length=100), nullable=True),
    sa.Column('anno_produzione', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autoclavi_codice'), 'autoclavi', ['codice'], unique=True)
    op.create_index(op.f('ix_autoclavi_id'), 'autoclavi', ['id'], unique=False)
    op.create_index(op.f('ix_autoclavi_nome'), 'autoclavi', ['nome'], unique=True)
    op.create_table('cataloghi',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('sotto_categoria', sa.String(length=100), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('lunghezza', sa.Float(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('part_number')
    )
    op.create_index(op.f('ix_cataloghi_part_number'), 'cataloghi', ['part_number'], unique=False)
    op.create_table('cicli_cura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('temperatura_stasi1', sa.Float(), nullable=False),
    sa.Column('pressione_stasi1', sa.Float(), nullable=False),
    sa.Column('durata_stasi1', sa.Integer(), nullable=False),
    sa.Column('attiva_stasi2', sa.Boolean(), nullable=False),
    sa.Column('temperatura_stasi2', sa.Float(), nullable=True),
    sa.Column('pressione_stasi2', sa.Float(), nullable=True),
    sa.Column('durata_stasi2', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_cicli_cura_id'), 'cicli_cura', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.Enum('produzione', 'qualita', 'tempi', 'completo', 'nesting', name='reporttypeenum'), nullable=False),
    sa.Column('generated_for_user_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('include_sections', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_filename'), 'reports', ['filename'], unique=True)
    op.create_index(op.f('ix_reports_generated_for_user_id'), 'reports', ['generated_for_user_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('tempi_produzione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('sotto_categoria', sa.String(length=100), nullable=True),
    sa.Column('tempo_medio_minuti', sa.Float(), nullable=False),
    sa.Column('tempo_minimo_minuti', sa.Float(), nullable=True),
    sa.Column('tempo_massimo_minuti', sa.Float(), nullable=True),
    sa.Column('numero_osservazioni', sa.Integer(), nullable=False),
    sa.Column('ultima_osservazione', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categoria_sotto_categoria', 'tempi_produzione', ['categoria', 'sotto_categoria'], unique=False)
    op.create_index('idx_part_number_categoria', 'tempi_produzione', ['part_number', 'categoria'], unique=False)
    op.create_index(op.f('ix_tempi_produzione_categoria'), 'tempi_produzione', ['categoria'], unique=False)
    op.create_index(op.f('ix_tempi_produzione_id'), 'tempi_produzione', ['id'], unique=False)
    op.create_index(op.f('ix_tempi_produzione_part_number'), 'tempi_produzione', ['part_number'], unique=False)
    op.create_index(op.f('ix_tempi_produzione_sotto_categoria'), 'tempi_produzione', ['sotto_categoria'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number_tool', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('lunghezza_piano', sa.Float(), nullable=False),
    sa.Column('larghezza_piano', sa.Float(), nullable=False),
    sa.Column('disponibile', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number_tool')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('nesting_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autoclave_id', sa.Integer(), nullable=True),
    sa.Column('odl_ids', sa.JSON(), nullable=True),
    sa.Column('odl_esclusi_ids', sa.JSON(), nullable=True),
    sa.Column('motivi_esclusione', sa.JSON(), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=False),
    sa.Column('confermato_da_ruolo', sa.String(length=50), nullable=True),
    sa.Column('area_utilizzata', sa.Float(), nullable=True),
    sa.Column('area_totale', sa.Float(), nullable=True),
    sa.Column('valvole_utilizzate', sa.Integer(), nullable=True),
    sa.Column('valvole_totali', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('posizioni_tool', sa.JSON(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autoclave_id'], ['autoclavi.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nesting_results_autoclave_id'), 'nesting_results', ['autoclave_id'], unique=False)
    op.create_index(op.f('ix_nesting_results_id'), 'nesting_results', ['id'], unique=False)
    op.create_index(op.f('ix_nesting_results_report_id'), 'nesting_results', ['report_id'], unique=False)
    op.create_table('parti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('descrizione_breve', sa.String(length=255), nullable=False),
    sa.Column('num_valvole_richieste', sa.Integer(), nullable=False),
    sa.Column('ciclo_cura_id', sa.Integer(), nullable=True),
    sa.Column('note_produzione', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_cura_id'], ['cicli_cura.id'], ),
    sa.ForeignKeyConstraint(['part_number'], ['cataloghi.part_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parti_id'), 'parti', ['id'], unique=False)
    op.create_index(op.f('ix_parti_part_number'), 'parti', ['part_number'], unique=False)
    op.create_table('odl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parte_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('priorita', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Preparazione', 'Laminazione', 'In Coda', 'Attesa Cura', 'Cura', 'Finito', name='odl_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('motivo_blocco', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parte_id'], ['parti.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odl_id'), 'odl', ['id'], unique=False)
    op.create_index(op.f('ix_odl_parte_id'), 'odl', ['parte_id'], unique=False)
    op.create_index(op.f('ix_odl_tool_id'), 'odl', ['tool_id'], unique=False)
    op.create_table('parte_tool_association',
    sa.Column('parte_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parte_id'], ['parti.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('parte_id', 'tool_id')
    )
    op.create_table('nesting_result_odl',
    sa.Column('nesting_result_id', sa.Integer(), nullable=False),
    sa.Column('odl_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nesting_result_id'], ['nesting_results.id'], ),
    sa.ForeignKeyConstraint(['odl_id'], ['odl.id'], ),
    sa.PrimaryKeyConstraint('nesting_result_id', 'odl_id')
    )
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('odl_id', sa.Integer(), nullable=True),
    sa.Column('autoclave_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('sotto_categoria', sa.String(length=100), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('priority_override', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_frequency', sa.String(length=50), nullable=True),
    sa.Column('pieces_per_month', sa.Integer(), nullable=True),
    sa.Column('parent_schedule_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autoclave_id'], ['autoclavi.id'], ),
    sa.ForeignKeyConstraint(['odl_id'], ['odl.id'], ),
    sa.ForeignKeyConstraint(['parent_schedule_id'], ['schedule_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_entries_autoclave_id'), 'schedule_entries', ['autoclave_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_categoria'), 'schedule_entries', ['categoria'], unique=False)
    op.create_index(op.f('ix_schedule_entries_id'), 'schedule_entries', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_odl_id'), 'schedule_entries', ['odl_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_sotto_categoria'), 'schedule_entries', ['sotto_categoria'], unique=False)
    op.create_table('tempo_fasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odl_id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.Enum('laminazione', 'attesa_cura', 'cura', name='tipo_fase'), nullable=False),
    sa.Column('inizio_fase', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fine_fase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('durata_minuti', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['odl_id'], ['odl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tempo_fasi_id'), 'tempo_fasi', ['id'], unique=False)
    op.create_index(op.f('ix_tempo_fasi_odl_id'), 'tempo_fasi', ['odl_id'], unique=False)
    op.create_table('odl_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odl_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('stato_precedente', sa.String(length=50), nullable=True),
    sa.Column('stato_nuovo', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('responsabile', sa.String(length=100), nullable=True),
    sa.Column('nesting_id', sa.Integer(), nullable=True),
    sa.Column('autoclave_id', sa.Integer(), nullable=True),
    sa.Column('schedule_entry_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autoclave_id'], ['autoclavi.id'], ),
    sa.ForeignKeyConstraint(['nesting_id'], ['nesting_results.id'], ),
    sa.ForeignKeyConstraint(['odl_id'], ['odl.id'], ),
    sa.ForeignKeyConstraint(['schedule_entry_id'], ['schedule_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odl_logs_autoclave_id'), 'odl_logs', ['autoclave_id'], unique=False)
    op.create_index(op.f('ix_odl_logs_id'), 'odl_logs', ['id'], unique=False)
    op.create_index(op.f('ix_odl_logs_nesting_id'), 'odl_logs', ['nesting_id'], unique=False)
    op.create_index(op.f('ix_odl_logs_odl_id'), 'odl_logs', ['odl_id'], unique=False)
    op.create_index(op.f('ix_odl_logs_schedule_entry_id'), 'odl_logs', ['schedule_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odl_logs_schedule_entry_id'), table_name='odl_logs')
    op.drop_index(op.f('ix_odl_logs_odl_id'), table_name='odl_logs')
    op.drop_index(op.f('ix_odl_logs_nesting_id'), table_name='odl_logs')
    op.drop_index(op.f('ix_odl_logs_id'), table_name='odl_logs')
    op.drop_index(op.f('ix_odl_logs_autoclave_id'), table_name='odl_logs')
    op.drop_table('odl_logs')
    op.drop_index(op.f('ix_tempo_fasi_odl_id'), table_name='tempo_fasi')
    op.drop_index(op.f('ix_tempo_fasi_id'), table_name='tempo_fasi')
    op.drop_table('tempo_fasi')
    op.drop_index(op.f('ix_schedule_entries_sotto_categoria'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_odl_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_categoria'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_autoclave_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_table('nesting_result_odl')
    op.drop_table('parte_tool_association')
    op.drop_index(op.f('ix_odl_tool_id'), table_name='odl')
    op.drop_index(op.f('ix_odl_parte_id'), table_name='odl')
    op.drop_index(op.f('ix_odl_id'), table_name='odl')
    op.drop_table('odl')
    op.drop_index(op.f('ix_parti_part_number'), table_name='parti')
    op.drop_index(op.f('ix_parti_id'), table_name='parti')
    op.drop_table('parti')
    op.drop_index(op.f('ix_nesting_results_report_id'), table_name='nesting_results')
    op.drop_index(op.f('ix_nesting_results_id'), table_name='nesting_results')
    op.drop_index(op.f('ix_nesting_results_autoclave_id'), table_name='nesting_results')
    op.drop_table('nesting_results')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_tempi_produzione_sotto_categoria'), table_name='tempi_produzione')
    op.drop_index(op.f('ix_tempi_produzione_part_number'), table_name='tempi_produzione')
    op.drop_index(op.f('ix_tempi_produzione_id'), table_name='tempi_produzione')
    op.drop_index(op.f('ix_tempi_produzione_categoria'), table_name='tempi_produzione')
    op.drop_index('idx_part_number_categoria', table_name='tempi_produzione')
    op.drop_index('idx_categoria_sotto_categoria', table_name='tempi_produzione')
    op.drop_table('tempi_produzione')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_for_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_filename'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_cicli_cura_id'), table_name='cicli_cura')
    op.drop_table('cicli_cura')
    op.drop_index(op.f('ix_cataloghi_part_number'), table_name='cataloghi')
    op.drop_table('cataloghi')
    op.drop_index(op.f('ix_autoclavi_nome'), table_name='autoclavi')
    op.drop_index(op.f('ix_autoclavi_id'), table_name='autoclavi')
    op.drop_index(op.f('ix_autoclavi_codice'), table_name='autoclavi')
    op.drop_table('autoclavi')
    # ### end Alembic commands ###
